import React, { useEffect, useState } from 'react';
import { useSearchParams, useNavigate, Link } from 'react-router-dom';
import api from '../services/api';
import Card from '../components/Card';
import Button from '../components/Button';
import { Award, Target, BookOpen, MessageSquare, ArrowLeft, Loader2 } from 'lucide-react';

const Feedback = () => {
  const [searchParams] = useSearchParams();
  const roomId = searchParams.get('roomId');
  const navigate = useNavigate();
  
  const [feedbacks, setFeedbacks] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    if (!roomId) {
      navigate('/dashboard');
      return;
    }
    fetchFeedback();
  }, [roomId]);

  const fetchFeedback = async () => {
    try {
      const response = await api.post('/feedback', { roomId });
      setFeedbacks(response.data);
    } catch (err) {
      setError(err.response?.data?.error || 'Failed to generate feedback. Ensure Groq API Key is configured in backend.');
    } finally {
      setLoading(false);
    }
  };

  const ScoreCircle = ({ score, label }) => {
    const colorClass = score >= 8 ? 'text-green-500 border-green-500' : score >= 5 ? 'text-yellow-500 border-yellow-500' : 'text-red-500 border-red-500';
    return (
      <div className="flex flex-col items-center">
        <div className={`w-14 h-14 rounded-full border-4 flex items-center justify-center font-bold text-xl mb-1 ${colorClass}`}>
          {score}
        </div>
        <span className="text-xs text-gray-500 font-medium text-center uppercase">{label}</span>
      </div>
    );
  };

  if (loading) {
    return (
      <div className="min-h-[calc(100vh-4rem)] flex flex-col items-center justify-center bg-gray-50">
        <Loader2 className="w-12 h-12 text-blue-600 animate-spin mb-4" />
        <h2 className="text-xl font-semibold text-gray-900">AI is analyzing the discussion...</h2>
        <p className="text-gray-500 mt-2">This may take a few moments.</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-[calc(100vh-4rem)] flex flex-col items-center justify-center bg-gray-50 p-4 text-center">
        <div className="bg-red-50 text-red-600 p-6 rounded-2xl max-w-md w-full border border-red-100 shadow-sm">
          <h2 className="text-lg font-bold mb-2">Analysis Failed</h2>
          <p className="text-sm">{error}</p>
          <Link to="/dashboard" className="mt-6 inline-block">
            <Button variant="secondary">Return to Dashboard</Button>
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-[calc(100vh-4rem)] bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-6xl mx-auto space-y-8">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-extrabold text-gray-900 tracking-tight">AI Evaluation Report</h1>
            <p className="mt-2 text-gray-500">Detailed feedback generated by HR Assistant Model.</p>
          </div>
          <Link to="/dashboard">
            <Button variant="outline" className="flex items-center gap-2">
              <ArrowLeft className="w-4 h-4" /> Back to Dashboard
            </Button>
          </Link>
        </div>

        <div className="space-y-6">
          {feedbacks.map((fb, idx) => (
            <Card key={idx} className="overflow-hidden hover:shadow-md transition-shadow">
              <div className="flex flex-col lg:flex-row gap-8">
                {/* Left column: Overview & Scores */}
                <div className="lg:w-1/3 flex flex-col gap-6">
                  <div>
                    <h2 className="text-2xl font-bold text-gray-900">{fb.userName}</h2>
                    <p className="text-sm text-gray-500 mt-1">Participant Evaluation</p>
                  </div>
                  
                  <div className="grid grid-cols-2 gap-4 bg-gray-50 p-4 rounded-xl border border-gray-100">
                    <ScoreCircle score={fb.communicationScore} label="Communication" />
                    <ScoreCircle score={fb.confidenceScore} label="Confidence" />
                    <ScoreCircle score={fb.grammarScore} label="Grammar" />
                    <ScoreCircle score={fb.participationScore} label="Participation" />
                  </div>
                </div>

                {/* Right column: Detailed Analysis */}
                <div className="lg:w-2/3 flex flex-col gap-6">
                  <div className="bg-blue-50/50 p-5 rounded-xl border border-blue-100">
                    <h3 className="text-sm font-bold text-blue-900 uppercase flex items-center gap-2 mb-2">
                      <MessageSquare className="w-4 h-4" /> Executive Summary
                    </h3>
                    <p className="text-gray-700 text-sm leading-relaxed">{fb.summary}</p>
                  </div>
                  
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div className="space-y-3">
                      <h3 className="text-sm font-bold text-green-700 uppercase flex items-center gap-2">
                        <Award className="w-4 h-4" /> Key Strengths
                      </h3>
                      <ul className="space-y-2">
                        {fb.strengths.map((str, i) => (
                          <li key={i} className="flex items-start gap-2 text-sm text-gray-700 bg-white border border-gray-100 p-2.5 rounded-lg shadow-sm">
                            <span className="text-green-500 font-bold mt-0.5">•</span> 
                            <span>{str}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                    
                    <div className="space-y-3">
                      <h3 className="text-sm font-bold text-yellow-700 uppercase flex items-center gap-2">
                        <Target className="w-4 h-4" /> Areas for Improvement
                      </h3>
                      <ul className="space-y-2">
                        {fb.improvements.map((imp, i) => (
                          <li key={i} className="flex items-start gap-2 text-sm text-gray-700 bg-white border border-gray-100 p-2.5 rounded-lg shadow-sm">
                            <span className="text-yellow-500 font-bold mt-0.5">•</span> 
                            <span>{imp}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </Card>
          ))}
        </div>
      </div>
    </div>
  );
};

export default Feedback;
