import React from 'react';
import { Link } from 'react-router-dom';
import { Users, Mic, BarChart3 } from 'lucide-react';
import Button from '../components/Button';

const Landing = () => {
  return (
    <div className="min-h-screen bg-gradient-to-b from-blue-50 to-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-20 pb-16 text-center">
        <h1 className="text-5xl font-extrabold tracking-tight text-gray-900 sm:text-6xl mb-6">
          Elevate Your <span className="text-blue-600">Group Discussions</span>
        </h1>
        <p className="mt-4 max-w-2xl text-xl text-gray-500 mx-auto mb-10">
          The ultimate platform for conducting and analyzing group discussions. 
          Real-time transcripts, structured buzzer system, and AI-powered feedback for every participant.
        </p>
        
        <div className="flex justify-center gap-4 mb-20">
          <Link to="/register">
            <Button className="px-8 py-3 text-lg rounded-xl shadow-lg hover:shadow-xl hover:-translate-y-0.5 transition-all">
              Get Started
            </Button>
          </Link>
          <Link to="/login">
            <Button variant="outline" className="px-8 py-3 text-lg rounded-xl bg-white hover:bg-gray-50 transition-all">
              Login
            </Button>
          </Link>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-5xl mx-auto">
          <div className="bg-white p-8 rounded-2xl shadow-sm border border-gray-100 hover:shadow-md transition-shadow">
            <div className="w-12 h-12 bg-blue-100 text-blue-600 rounded-xl flex items-center justify-center mb-6 mx-auto">
              <Users className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-bold text-gray-900 mb-3">Structured GDs</h3>
            <p className="text-gray-500 text-sm">
              Organized buzzer system ensures only one person speaks at a time, preventing overlapping chaos.
            </p>
          </div>
          <div className="bg-white p-8 rounded-2xl shadow-sm border border-gray-100 hover:shadow-md transition-shadow">
            <div className="w-12 h-12 bg-blue-100 text-blue-600 rounded-xl flex items-center justify-center mb-6 mx-auto">
              <Mic className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-bold text-gray-900 mb-3">Live Transcripts</h3>
            <p className="text-gray-500 text-sm">
              Everything spoken is converted to text in real-time, creating an accurate log of the discussion.
            </p>
          </div>
          <div className="bg-white p-8 rounded-2xl shadow-sm border border-gray-100 hover:shadow-md transition-shadow">
            <div className="w-12 h-12 bg-blue-100 text-blue-600 rounded-xl flex items-center justify-center mb-6 mx-auto">
              <BarChart3 className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-bold text-gray-900 mb-3">AI HR Feedback</h3>
            <p className="text-gray-500 text-sm">
              Receive detailed, personalized HR-level feedback automatically generated by Groq AI models.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Landing;
